Update some links from bitbucket to GitHub
elmah/www pull request #45
Opened 2020-08-19 23:00 UTC by Banner-Keith

I could not find equivalent links for all of these. But I put in the ones I did find.

2020-08-20 08:26 UTC, atifaziz requested changes
Thank you this PR. I have suggested edits because pointing to `master` is never a good idea since the cheese could get moved and then those links will go 404. I have essentially pinned the links to the [`v1.2-sp2` tag](https://github.com/elmah/Elmah/releases/tag/v1.2-sp2) instead.

2020-08-20 08:26 UTC, atifaziz commented on Downloads.md
> +  * [Sources](https://bitbucket.org/project-elmah/main/downloads/ELMAH-1.0-src.zip)
This seems like a whitespace change only. Can we revert this, please?

2020-08-20 08:26 UTC, atifaziz commented on Downloads.md
> +| [Microsoft SQL Server](http://www.microsoft.com/sqlserver/) | Included in .NET Framework | [MS SQL Server DDL Script](https://github.com/elmah/SqlErrorLog/blob/master/src/SQLServer.sql) | - |
```suggestion
| [Microsoft SQL Server](http://www.microsoft.com/sqlserver/) | Included in .NET Framework | [MS SQL Server DDL Script](https://github.com/elmah/Elmah/blob/v1.2-sp2/src/Elmah/SQLServer.sql) | - |
```

2020-08-20 08:26 UTC, atifaziz commented on Downloads.md
> +| [MySQL](http://www.mysql.com/) | [MySQL Binaries](https://bitbucket.org/project-elmah/main/downloads/ELMAH-1.2-lib-MySql.zip) | [MySQL DDL Script](https://github.com/elmah/MySqlErrorLog/blob/master
```suggestion
| [MySQL](http://www.mysql.com/) | [MySQL Binaries](https://bitbucket.org/project-elmah/main/downloads/ELMAH-1.2-lib-MySql.zip) | [MySQL DDL Script](https://github.com/elmah/Elmah/blob/v1.2-sp2/src/Elmah/MySql.sql) | - |
```

2020-08-20 08:26 UTC, atifaziz commented on Downloads.md
> +| [PostgreSQL](http://www.postgresql.org/) | [PostgreSQL Binaries](https://bitbucket.org/project-elmah/main/downloads/ELMAH-1.2-lib-Pgsql.zip) | [PostgreSQL DDL Script](https://github.com/elmah/Pgsql
```suggestion
| [PostgreSQL](http://www.postgresql.org/) | [PostgreSQL Binaries](https://bitbucket.org/project-elmah/main/downloads/ELMAH-1.2-lib-Pgsql.zip) | [PostgreSQL DDL Script](https://github.com/elmah/Elmah/blob/v1.2-sp2/src/Elmah/Pgsql.sql) | - |
```

2020-09-02 00:18 UTC, Banner-Keith commented
@atifaziz I have committed your changes and reverted the new line character at the end of the file.

2020-09-02 07:55 UTC, atifaziz approved these changes
Thank you again for those updates and follow-up!

2020-09-02 08:11 UTC, merged